"""
suites/gherkin_features.py
==========================
Validates .feature (Gherkin/BDD) files generated by ava-qa-scenario-generator.

Checks applied (mapped to scenario-generator-checklist.md):
  CHK-COUNT     — minimum 15 scenarios total
  CHK-HAPPY     — every feature has ≥ 1 @happy scenario
  CHK-SAD       — every feature has ≥ 1 @sad scenario
  CHK-GHERKIN   — every scenario follows Given → When → Then order
  CHK-AMBIGUITY — no duplicate step text with different meanings across features
  CHK-TAGS      — every scenario has ≥ 2 tags (classification + module)
  CHK-OUTLINE   — candidates for Scenario Outline detected
  CHK-THEN      — every scenario has at least one Then step
  CHK-SPECFLOW  — syntax compatible with SpecFlow/Cucumber parser
  CHK-STEPS     — max 10 steps per scenario
  CHK-I18N      — keywords match project language (en/pt)

Usage (standalone):
    python -m src.shared.checks --project Meu-ERP --suite gherkin

Usage (programmatic):
    from src.shared.checks.suites.gherkin_features import GherkinFeaturesSuite
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from src.shared.checks.context import CheckContext
    from src.shared.checks.reporter import Reporter

# ── Constants ────────────────────────────────────────────────────────────────

_MIN_SCENARIOS = 15
_MAX_STEPS_PER_SCENARIO = 10

# Gherkin keywords by language
_KEYWORDS = {
    "en": {
        "feature": re.compile(r"^\s*Feature:\s*(.+)", re.IGNORECASE),
        "background": re.compile(r"^\s*Background:\s*", re.IGNORECASE),
        "scenario": re.compile(r"^\s*Scenario:\s*(.+)", re.IGNORECASE),
        "scenario_outline": re.compile(
            r"^\s*Scenario Outline:\s*(.+)", re.IGNORECASE
        ),
        "examples": re.compile(r"^\s*Examples:\s*", re.IGNORECASE),
        "given": re.compile(r"^\s*Given\s+(.+)", re.IGNORECASE),
        "when": re.compile(r"^\s*When\s+(.+)", re.IGNORECASE),
        "then": re.compile(r"^\s*Then\s+(.+)", re.IGNORECASE),
        "and": re.compile(r"^\s*And\s+(.+)", re.IGNORECASE),
        "but": re.compile(r"^\s*But\s+(.+)", re.IGNORECASE),
    },
    "pt": {
        "feature": re.compile(r"^\s*Funcionalidade:\s*(.+)", re.IGNORECASE),
        "background": re.compile(r"^\s*Contexto:\s*", re.IGNORECASE),
        "scenario": re.compile(r"^\s*Cen[aá]rio:\s*(.+)", re.IGNORECASE),
        "scenario_outline": re.compile(
            r"^\s*Esquema do Cen[aá]rio:\s*(.+)", re.IGNORECASE
        ),
        "examples": re.compile(r"^\s*Exemplos:\s*", re.IGNORECASE),
        "given": re.compile(r"^\s*Dado\s+(.+)", re.IGNORECASE),
        "when": re.compile(r"^\s*Quando\s+(.+)", re.IGNORECASE),
        "then": re.compile(r"^\s*Ent[aã]o\s+(.+)", re.IGNORECASE),
        "and": re.compile(r"^\s*E\s+(.+)", re.IGNORECASE),
        "but": re.compile(r"^\s*Mas\s+(.+)", re.IGNORECASE),
    },
}

# Tags considered as classification tags
_CLASSIFICATION_TAGS = {"@happy", "@sad", "@edge", "@smoke", "@regression"}

# Regex: tag on a line (e.g., @happy @module-name)
_TAG_RE = re.compile(r"@[\w-]+")

# Characters that break SpecFlow/Cucumber parsing
_SPECFLOW_BAD_CHARS = re.compile(r"[<>](?![^<]*>)")  # unmatched angle brackets


# ── Data classes ─────────────────────────────────────────────────────────────


@dataclass
class ParsedStep:
    keyword: str  # given | when | then | and | but
    text: str
    line_no: int
    inherits: str = ""  # resolved keyword (and/but → parent given/when/then)


@dataclass
class ParsedScenario:
    name: str
    line_no: int
    tags: list[str] = field(default_factory=list)
    steps: list[ParsedStep] = field(default_factory=list)
    is_outline: bool = False
    has_examples: bool = False
    feature_name: str = ""
    file_path: str = ""


@dataclass
class ParsedFeature:
    name: str
    file_path: str
    scenarios: list[ParsedScenario] = field(default_factory=list)
    has_background: bool = False


# ── Parser ───────────────────────────────────────────────────────────────────


def _detect_language(lines: list[str]) -> str:
    """Detect Gherkin language from file content. Default: en."""
    for line in lines[:30]:
        stripped = line.strip()
        if stripped.startswith("# language:"):
            lang = stripped.split(":", 1)[1].strip()
            if lang in _KEYWORDS:
                return lang
        if _KEYWORDS["pt"]["feature"].match(stripped):
            return "pt"
        if _KEYWORDS["en"]["feature"].match(stripped):
            return "en"
    return "en"


def _parse_feature_file(path: Path) -> Optional[ParsedFeature]:
    """Parse a single .feature file into structured data."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    lines = text.splitlines()
    lang = _detect_language(lines)
    kw = _KEYWORDS[lang]

    feature: Optional[ParsedFeature] = None
    current_scenario: Optional[ParsedScenario] = None
    pending_tags: list[str] = []
    last_step_keyword = ""

    for i, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()

        # Skip comments and empty lines
        if not line or line.startswith("#"):
            continue

        # Collect tags
        if line.startswith("@"):
            pending_tags.extend(_TAG_RE.findall(line))
            continue

        # Feature
        m = kw["feature"].match(line)
        if m:
            feature = ParsedFeature(
                name=m.group(1).strip(),
                file_path=str(path),
            )
            pending_tags.clear()
            continue

        if feature is None:
            continue

        # Background
        if kw["background"].match(line):
            feature.has_background = True
            current_scenario = None
            last_step_keyword = ""
            pending_tags.clear()
            continue

        # Scenario Outline
        m = kw["scenario_outline"].match(line)
        if m:
            current_scenario = ParsedScenario(
                name=m.group(1).strip(),
                line_no=i,
                tags=list(pending_tags),
                is_outline=True,
                feature_name=feature.name,
                file_path=str(path),
            )
            feature.scenarios.append(current_scenario)
            pending_tags.clear()
            last_step_keyword = ""
            continue

        # Scenario
        m = kw["scenario"].match(line)
        if m:
            current_scenario = ParsedScenario(
                name=m.group(1).strip(),
                line_no=i,
                tags=list(pending_tags),
                feature_name=feature.name,
                file_path=str(path),
            )
            feature.scenarios.append(current_scenario)
            pending_tags.clear()
            last_step_keyword = ""
            continue

        # Examples
        if kw["examples"].match(line):
            if current_scenario and current_scenario.is_outline:
                current_scenario.has_examples = True
            continue

        if current_scenario is None:
            continue

        # Steps
        for step_type in ("given", "when", "then", "and", "but"):
            m = kw[step_type].match(line)
            if m:
                resolved = step_type
                if step_type in ("and", "but"):
                    resolved = last_step_keyword if last_step_keyword else "given"
                else:
                    last_step_keyword = step_type

                current_scenario.steps.append(
                    ParsedStep(
                        keyword=step_type,
                        text=m.group(1).strip(),
                        line_no=i,
                        inherits=resolved,
                    )
                )
                break

    return feature


# ── Suite ────────────────────────────────────────────────────────────────────


class GherkinFeaturesSuite:
    NAME = "gherkin"

    def __init__(self, ctx: "CheckContext") -> None:
        self.ctx = ctx
        self._features_dir = ctx.outputs_dir / "tobe" / "tests" / "features"
        self._qa_dir = ctx.outputs_dir / "qa" / "scenario-generator"

    def _find_feature_files(self) -> list[Path]:
        if not self._features_dir.exists():
            return []
        return sorted(self._features_dir.glob("*.feature"))

    def run(self, reporter: "Reporter") -> None:
        files = self._find_feature_files()
        print(f"\n── Suite: {self.NAME}  [{len(files)} .feature file(s)] ──")

        if not files:
            reporter.record(
                self.NAME,
                "feature files found",
                False,
                f"no .feature files in {self._features_dir}",
            )
            return

        # Parse all files
        features: list[ParsedFeature] = []
        for f in files:
            parsed = _parse_feature_file(f)
            if parsed:
                features.append(parsed)
            else:
                reporter.record(
                    self.NAME,
                    f"parse {f.name}",
                    False,
                    "failed to read or parse file",
                )

        all_scenarios = [s for feat in features for s in feat.scenarios]

        # ── CHK-COUNT: minimum scenario count ────────────────────────
        total = len(all_scenarios)
        reporter.record(
            self.NAME,
            "CHK-COUNT: min 15 scenarios",
            total >= _MIN_SCENARIOS,
            f"{total} scenarios found",
        )

        # ── CHK-HAPPY: every feature has ≥ 1 @happy ─────────────────
        missing_happy = [
            f.name
            for f in features
            if not any("@happy" in s.tags for s in f.scenarios)
        ]
        reporter.record(
            self.NAME,
            "CHK-HAPPY: happy path per feature",
            len(missing_happy) == 0,
            f"missing in: {', '.join(missing_happy)}" if missing_happy else "all covered",
        )

        # ── CHK-SAD: every feature has ≥ 1 @sad ─────────────────────
        missing_sad = [
            f.name
            for f in features
            if not any("@sad" in s.tags for s in f.scenarios)
        ]
        reporter.record(
            self.NAME,
            "CHK-SAD: sad path per feature",
            len(missing_sad) == 0,
            f"missing in: {', '.join(missing_sad)}" if missing_sad else "all covered",
        )

        # ── CHK-GHERKIN: Given → When → Then order ──────────────────
        bad_order: list[str] = []
        for s in all_scenarios:
            resolved = [st.inherits for st in s.steps]
            order_map = {"given": 0, "when": 1, "then": 2}
            max_seen = -1
            valid = True
            for r in resolved:
                level = order_map.get(r, -1)
                if level < max_seen and level != -1:
                    valid = False
                    break
                if level > max_seen:
                    max_seen = level
            if not valid:
                bad_order.append(f"{s.feature_name}:{s.name} (line {s.line_no})")

        reporter.record(
            self.NAME,
            "CHK-GHERKIN: Given→When→Then order",
            len(bad_order) == 0,
            f"{len(bad_order)} violations: {'; '.join(bad_order[:5])}"
            if bad_order
            else "all valid",
        )

        # ── CHK-AMBIGUITY: no duplicate step text across features ────
        step_map: dict[str, set[str]] = {}
        for s in all_scenarios:
            for st in s.steps:
                normalized = st.text.lower().strip()
                step_map.setdefault(normalized, set()).add(s.feature_name)
        ambiguous = {
            text: feats for text, feats in step_map.items() if len(feats) > 1
        }
        reporter.record(
            self.NAME,
            "CHK-AMBIGUITY: no cross-feature duplicate steps",
            len(ambiguous) == 0,
            f"{len(ambiguous)} ambiguous steps found"
            if ambiguous
            else "no ambiguity",
        )

        # ── CHK-TAGS: ≥ 2 tags per scenario ─────────────────────────
        under_tagged = [
            f"{s.feature_name}:{s.name}"
            for s in all_scenarios
            if len(s.tags) < 2
        ]
        reporter.record(
            self.NAME,
            "CHK-TAGS: ≥ 2 tags per scenario",
            len(under_tagged) == 0,
            f"{len(under_tagged)} scenarios with < 2 tags"
            if under_tagged
            else "all tagged",
        )

        # ── CHK-TAGS classification: has classification + module ─────
        no_classification = [
            f"{s.feature_name}:{s.name}"
            for s in all_scenarios
            if not any(t in _CLASSIFICATION_TAGS for t in s.tags)
        ]
        reporter.record(
            self.NAME,
            "CHK-TAGS: classification tag present",
            len(no_classification) == 0,
            f"{len(no_classification)} scenarios missing classification tag"
            if no_classification
            else "all classified",
        )

        # ── CHK-THEN: every scenario has at least one Then ───────────
        no_then = [
            f"{s.feature_name}:{s.name} (line {s.line_no})"
            for s in all_scenarios
            if not any(st.inherits == "then" for st in s.steps)
        ]
        reporter.record(
            self.NAME,
            "CHK-THEN: Then step present",
            len(no_then) == 0,
            f"{len(no_then)} scenarios without Then: {'; '.join(no_then[:5])}"
            if no_then
            else "all have Then",
        )

        # ── CHK-SPECFLOW: no bad characters in steps ────────────────
        specflow_issues: list[str] = []
        for s in all_scenarios:
            for st in s.steps:
                if _SPECFLOW_BAD_CHARS.search(st.text):
                    specflow_issues.append(
                        f"{s.feature_name}:{s.name} line {st.line_no}"
                    )
        reporter.record(
            self.NAME,
            "CHK-SPECFLOW: SpecFlow/Cucumber syntax",
            len(specflow_issues) == 0,
            f"{len(specflow_issues)} syntax issues"
            if specflow_issues
            else "syntax OK",
        )

        # ── CHK-STEPS: max steps per scenario ───────────────────────
        over_steps = [
            f"{s.feature_name}:{s.name} ({len(s.steps)} steps)"
            for s in all_scenarios
            if len(s.steps) > _MAX_STEPS_PER_SCENARIO
        ]
        reporter.record(
            self.NAME,
            f"CHK-STEPS: max {_MAX_STEPS_PER_SCENARIO} steps",
            len(over_steps) == 0,
            f"{len(over_steps)} scenarios exceed limit"
            if over_steps
            else "all within limit",
        )

        # ── CHK-OUTLINE: outlines have Examples ─────────────────────
        outlines_no_examples = [
            f"{s.feature_name}:{s.name}"
            for s in all_scenarios
            if s.is_outline and not s.has_examples
        ]
        reporter.record(
            self.NAME,
            "CHK-OUTLINE: Scenario Outline has Examples",
            len(outlines_no_examples) == 0,
            f"{len(outlines_no_examples)} outlines without Examples"
            if outlines_no_examples
            else "all outlines valid",
        )
