"""
suites/tobe_db_type_target.py
=============================
Validates the TO-BE Database Type Target artifact
(``outputs/tobe/db/db-type-target.json``) generated by the
``ava-devops-iac`` agent.

Gates enforced:
  - File exists at the expected path.
  - File is valid JSON.
  - All required fields present: engine, version, tier,
    connection_string_template, pool_size, timeout_seconds, retry_count.
  - ``engine`` is one of the allowed values ("PostgreSQL", "Azure SQL").
  - ``version`` matches pattern ``\\d+(\\.\\d+)?``.
  - ``pool_size`` in range [1, 1024].
  - ``timeout_seconds`` in range [1, 300].
  - ``retry_count`` in range [0, 10].
  - ``connection_string_template`` contains placeholder markers (``{``).
  - ``connection_string_template`` does NOT contain hardcoded credentials.
  - ``generated_by`` equals "ava-devops-iac" or "ava-tobe-database-design" when present.
  - No additional unknown top-level keys beyond the schema.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    from src.shared.checks.context import CheckContext
    from src.shared.checks.reporter import Reporter

_REQUIRED_FIELDS = [
    "engine",
    "version",
    "tier",
    "connection_string_template",
    "pool_size",
    "timeout_seconds",
    "retry_count",
]

_ALLOWED_ENGINES = {"PostgreSQL", "Azure SQL"}

_VERSION_PATTERN = re.compile(r"^\d+(\.\d+)?$")

_ALLOWED_TOP_KEYS = {
    "engine", "version", "tier", "connection_string_template",
    "pool_size", "timeout_seconds", "retry_count",
    "adr_reference", "environments", "trace_id", "generated_by",
}

_ALLOWED_ENV_KEYS = {"dev", "staging", "production"}

_ALLOWED_ENV_OVERRIDE_KEYS = {"tier", "pool_size", "timeout_seconds", "retry_count"}

# Patterns that indicate hardcoded credentials in connection strings.
_CREDENTIAL_PATTERNS = [
    re.compile(r"Password\s*=\s*[^{][^;]+", re.IGNORECASE),
    re.compile(r"User\s+Id\s*=\s*[^{][^;]+", re.IGNORECASE),
    re.compile(r"pwd\s*=\s*[^{][^;]+", re.IGNORECASE),
    re.compile(r"uid\s*=\s*[^{][^;]+", re.IGNORECASE),
]


class TobeDbTypeTargetSuite:
    NAME = "tobe_db_type_target"

    def __init__(self, ctx: "CheckContext") -> None:
        self.ctx = ctx
        self.tobe_db_dir: Path = ctx.outputs_dir / "tobe" / "db"
        self.artifact_path: Path = self.tobe_db_dir / "db-type-target.json"

    # ------------------------------------------------------------------ #
    # Public entry point                                                   #
    # ------------------------------------------------------------------ #
    def run(self, reporter: "Reporter") -> None:
        print(f"\n-- Suite: {self.NAME} --")

        data = self._load_artifact(reporter)
        if data is None:
            return

        self._check_required_fields(reporter, data)
        self._check_engine(reporter, data)
        self._check_version(reporter, data)
        self._check_pool_size(reporter, data)
        self._check_timeout(reporter, data)
        self._check_retry_count(reporter, data)
        self._check_connection_string(reporter, data)
        self._check_generated_by(reporter, data)
        self._check_unknown_keys(reporter, data)
        self._check_environments(reporter, data)

    # ------------------------------------------------------------------ #
    # Individual checks                                                    #
    # ------------------------------------------------------------------ #
    def _load_artifact(self, reporter: "Reporter") -> Optional[dict]:
        if not self.artifact_path.exists():
            reporter.record(
                self.NAME, "artifact file exists", False,
                f"missing: {self.artifact_path.relative_to(self.ctx.REPO_ROOT)}",
            )
            return None
        reporter.record(self.NAME, "artifact file exists", True)

        raw = self.artifact_path.read_text(encoding="utf-8", errors="replace")
        try:
            data = json.loads(raw)
        except json.JSONDecodeError as e:
            reporter.record(
                self.NAME, "artifact is valid JSON", False, str(e),
            )
            return None
        reporter.record(self.NAME, "artifact is valid JSON", True)

        if not isinstance(data, dict):
            reporter.record(
                self.NAME, "artifact is a JSON object", False,
                f"got {type(data).__name__}",
            )
            return None
        return data

    def _check_required_fields(self, reporter: "Reporter", data: dict) -> None:
        missing = [f for f in _REQUIRED_FIELDS if f not in data]
        ok = not missing
        reporter.record(
            self.NAME, "required fields present", ok,
            "" if ok else f"missing: {', '.join(missing)}",
        )

    def _check_engine(self, reporter: "Reporter", data: dict) -> None:
        engine = data.get("engine")
        if engine is None:
            return  # already flagged by required-fields check
        ok = engine in _ALLOWED_ENGINES
        reporter.record(
            self.NAME, "engine is valid", ok,
            "" if ok else f"got '{engine}', expected one of {_ALLOWED_ENGINES}",
        )

    def _check_version(self, reporter: "Reporter", data: dict) -> None:
        version = data.get("version")
        if version is None:
            return
        ok = isinstance(version, str) and bool(_VERSION_PATTERN.match(version))
        reporter.record(
            self.NAME, "version format valid", ok,
            "" if ok else f"got '{version}', expected pattern 'd+(.d+)?'",
        )

    def _check_pool_size(self, reporter: "Reporter", data: dict) -> None:
        pool = data.get("pool_size")
        if pool is None:
            return
        ok = isinstance(pool, int) and 1 <= pool <= 1024
        reporter.record(
            self.NAME, "pool_size in range [1, 1024]", ok,
            "" if ok else f"got {pool!r}",
        )

    def _check_timeout(self, reporter: "Reporter", data: dict) -> None:
        timeout = data.get("timeout_seconds")
        if timeout is None:
            return
        ok = isinstance(timeout, int) and 1 <= timeout <= 300
        reporter.record(
            self.NAME, "timeout_seconds in range [1, 300]", ok,
            "" if ok else f"got {timeout!r}",
        )

    def _check_retry_count(self, reporter: "Reporter", data: dict) -> None:
        retry = data.get("retry_count")
        if retry is None:
            return
        ok = isinstance(retry, int) and 0 <= retry <= 10
        reporter.record(
            self.NAME, "retry_count in range [0, 10]", ok,
            "" if ok else f"got {retry!r}",
        )

    def _check_connection_string(self, reporter: "Reporter", data: dict) -> None:
        cs = data.get("connection_string_template")
        if cs is None:
            return
        if not isinstance(cs, str):
            reporter.record(
                self.NAME, "connection_string_template is string", False,
                f"got {type(cs).__name__}",
            )
            return

        # Must contain at least one placeholder
        has_placeholders = "{" in cs
        reporter.record(
            self.NAME, "connection_string_template has placeholders", has_placeholders,
            "" if has_placeholders else "no placeholder markers '{...}' found",
        )

        # Must NOT contain hardcoded credentials
        cred_matches = [
            p.pattern for p in _CREDENTIAL_PATTERNS if p.search(cs)
        ]
        no_creds = not cred_matches
        reporter.record(
            self.NAME, "connection_string_template has no hardcoded credentials", no_creds,
            "" if no_creds else f"credential patterns detected: {len(cred_matches)}",
        )

    def _check_generated_by(self, reporter: "Reporter", data: dict) -> None:
        gen = data.get("generated_by")
        if gen is None:
            return  # optional field
        allowed = {"ava-devops-iac", "ava-tobe-database-design"}
        ok = gen in allowed
        reporter.record(
            self.NAME, f"generated_by is one of {allowed}", ok,
            "" if ok else f"got '{gen}'",
        )

    def _check_unknown_keys(self, reporter: "Reporter", data: dict) -> None:
        unknown = set(data.keys()) - _ALLOWED_TOP_KEYS
        ok = not unknown
        reporter.record(
            self.NAME, "no unknown top-level keys", ok,
            "" if ok else f"unknown keys: {', '.join(sorted(unknown))}",
        )

    def _check_environments(self, reporter: "Reporter", data: dict) -> None:
        envs = data.get("environments")
        if envs is None:
            return  # optional field

        if not isinstance(envs, dict):
            reporter.record(
                self.NAME, "environments is an object", False,
                f"got {type(envs).__name__}",
            )
            return

        unknown_envs = set(envs.keys()) - _ALLOWED_ENV_KEYS
        ok_envs = not unknown_envs
        reporter.record(
            self.NAME, "environments keys are valid", ok_envs,
            "" if ok_envs else f"unknown environments: {', '.join(sorted(unknown_envs))}",
        )

        for env_name, env_data in envs.items():
            if env_name not in _ALLOWED_ENV_KEYS:
                continue
            if not isinstance(env_data, dict):
                reporter.record(
                    self.NAME, f"environments.{env_name} is an object", False,
                    f"got {type(env_data).__name__}",
                )
                continue
            unknown_override = set(env_data.keys()) - _ALLOWED_ENV_OVERRIDE_KEYS
            if unknown_override:
                reporter.record(
                    self.NAME, f"environments.{env_name} keys valid", False,
                    f"unknown keys: {', '.join(sorted(unknown_override))}",
                )
            # Validate override ranges
            self._check_env_override_ranges(reporter, env_name, env_data)

    def _check_env_override_ranges(self, reporter: "Reporter", env_name: str, env_data: dict) -> None:
        pool = env_data.get("pool_size")
        if pool is not None:
            ok = isinstance(pool, int) and 1 <= pool <= 1024
            if not ok:
                reporter.record(
                    self.NAME, f"environments.{env_name}.pool_size in range", False,
                    f"got {pool!r}",
                )

        timeout = env_data.get("timeout_seconds")
        if timeout is not None:
            ok = isinstance(timeout, int) and 1 <= timeout <= 300
            if not ok:
                reporter.record(
                    self.NAME, f"environments.{env_name}.timeout_seconds in range", False,
                    f"got {timeout!r}",
                )

        retry = env_data.get("retry_count")
        if retry is not None:
            ok = isinstance(retry, int) and 0 <= retry <= 10
            if not ok:
                reporter.record(
                    self.NAME, f"environments.{env_name}.retry_count in range", False,
                    f"got {retry!r}",
                )
