"""
suites/tobe_db_policy.py
========================
Validates the TO-BE Database Policy artifact (`outputs/tobe/db/sql-strategy.md`)
generated by the `ava-tobe-database-policy` agent (Fase 1.4 da esteira TO-BE).

Gates enforced:
  - Policy file exists.
  - Manifest exists, is valid JSON, and `template_version == policy_version`
    (the corporate version recorded in `src/shared/data/policies/sql-strategy.version`).
  - Policy file declares the same `policy_version` in its header.
  - Sections §1..§8 are all present.
  - History backup `.history/sql-strategy-{policy_version}-{trace_id}.md` exists.
  - No `FONTE AUSENTE` markers OR (if present) manifest flags
    `architecture_open_items: true` (consistency check).
  - Forbidden patterns absent: write-side views, residual SP-de-domínio refs.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from src.shared.checks.context import CheckContext
    from src.shared.checks.reporter import Reporter


_REQUIRED_SECTIONS = [
    r"^##\s*1\.\s*Introdu",
    r"^##\s*2\.\s*Princ",
    r"^##\s*3\.\s*Estrat",
    r"^##\s*4\.\s*Diretrizes",
    r"^##\s*5\.\s*Mapeamento",
    r"^##\s*6\.\s*Estrat[eé]gia\s+de\s+Backup",
    r"^##\s*7\.\s*Considera",
    r"^##\s*8\.\s*Conclus",
]

_VERSION_FILE_REL = Path("src/shared/data/policies/sql-strategy.version")


class TobeDbPolicySuite:
    NAME = "tobe_db_policy"

    def __init__(self, ctx: "CheckContext") -> None:
        self.ctx = ctx
        self.tobe_db_dir: Path = ctx.outputs_dir / "tobe" / "db"
        self.policy_path: Path = self.tobe_db_dir / "sql-strategy.md"
        self.manifest_path: Path = self.tobe_db_dir / "sql-strategy.manifest.json"
        self.history_dir: Path = self.tobe_db_dir / ".history"
        self.version_file: Path = ctx.REPO_ROOT / _VERSION_FILE_REL

    # ------------------------------------------------------------------ #
    def run(self, reporter: "Reporter") -> None:
        print(f"\n-- Suite: {self.NAME} --")

        corporate_version = self._read_corporate_version(reporter)
        if corporate_version is None:
            return

        if not self.policy_path.exists():
            reporter.record(
                self.NAME, "policy file exists", False,
                f"missing: {self.policy_path.relative_to(self.ctx.REPO_ROOT)}"
            )
            return
        reporter.record(self.NAME, "policy file exists", True)
        policy_text = self.policy_path.read_text(encoding="utf-8", errors="replace")

        manifest = self._load_manifest(reporter)
        self._check_manifest_versions(reporter, manifest, corporate_version)
        self._check_header_version(reporter, policy_text, corporate_version)
        self._check_sections(reporter, policy_text)
        self._check_history_backup(reporter, manifest, corporate_version)
        self._check_open_items(reporter, policy_text, manifest)
        self._check_forbidden_patterns(reporter, policy_text)

    # ------------------------------------------------------------------ #
    def _check_manifest_versions(self, reporter, manifest, corporate_version) -> None:
        if manifest is None:
            return
        mp = manifest.get("policy_version")
        mt = manifest.get("template_version")
        ok = mp == corporate_version and mt == corporate_version
        reporter.record(
            self.NAME, "manifest version sync", ok,
            "" if ok else
            f"corporate={corporate_version!r} policy_version={mp!r} template_version={mt!r}",
        )

    def _check_header_version(self, reporter, policy_text, corporate_version) -> None:
        ok, found = self._policy_header_version(policy_text, corporate_version)
        reporter.record(
            self.NAME, "policy header version matches corporate", ok,
            "" if ok else f"expected '{corporate_version}', found '{found}'",
        )

    def _check_sections(self, reporter, policy_text) -> None:
        missing = self._missing_sections(policy_text)
        reporter.record(
            self.NAME, "sections §1..§8 present", not missing,
            "" if not missing else f"missing sections: {missing}",
        )

    def _check_history_backup(self, reporter, manifest, corporate_version) -> None:
        if manifest is None:
            return
        trace_id = manifest.get("trace_id", "")
        expected = self.history_dir / f"sql-strategy-{corporate_version}-{trace_id}.md"
        ok = expected.exists()
        reporter.record(
            self.NAME, "history backup exists", ok,
            "" if ok else f"missing: {expected.relative_to(self.ctx.REPO_ROOT)}",
        )

    def _check_open_items(self, reporter, policy_text, manifest) -> None:
        has_marker = "[FONTE AUSENTE" in policy_text
        flagged = bool(manifest and manifest.get("architecture_open_items"))
        if has_marker:
            # Exception: FONTE AUSENTE entries that are annotated as confirmed-zero
            # (i.e. the source was confirmed absent in AS-IS, not a missing input)
            # do not require architecture_open_items: true.
            _CONFIRMED_ZERO_PATTERNS = (
                "não aplicável",
                "nao aplicavel",
                "confirmed",
                "confirmed-zero",
                "zero confirmado",
                "ausente confirmado",
                "inexistente no as-is",
            )
            confirmed_zero = all(
                any(p in block.lower() for p in _CONFIRMED_ZERO_PATTERNS)
                for block in policy_text.split("[FONTE AUSENTE")
                if block.strip()  # skip split artefact before first marker
                and "[FONTE AUSENTE" not in block  # ignore fragments without the marker itself
            )
            # Re-check: if every FONTE AUSENTE in the document carries a confirmed-zero
            # annotation, the flag is not required.
            if confirmed_zero and not flagged:
                reporter.record(
                    self.NAME, "open-items flagged when sources missing", True,
                    "[FONTE AUSENTE] markers present but all annotated as confirmed-zero — flag not required",
                )
            else:
                reporter.record(
                    self.NAME, "open-items flagged when sources missing", flagged,
                    "" if flagged else
                    "policy contains [FONTE AUSENTE] but manifest.architecture_open_items is not true",
                )
        else:
            reporter.record(self.NAME, "no FONTE AUSENTE markers", True)

    def _check_forbidden_patterns(self, reporter, policy_text) -> None:
        coverage_block = self._slice_section(policy_text, r"^###\s*5\.3\s*Resumo")
        if not coverage_block:
            return
        ws_views_violation = re.search(
            r"Views Write Side.*?\|\s*([1-9]\d*)\s*\|", coverage_block, re.DOTALL
        )
        ok = not bool(ws_views_violation)
        reporter.record(
            self.NAME, "no write-side views in coverage", ok,
            "" if ok else f"write-side views count > 0: {ws_views_violation.group(1)}",
        )

    # ------------------------------------------------------------------ #
    def _read_corporate_version(self, reporter: "Reporter") -> Optional[str]:
        if not self.version_file.exists():
            reporter.record(
                self.NAME, "corporate version file exists", False,
                f"missing: {self.version_file.relative_to(self.ctx.REPO_ROOT)}",
            )
            return None
        v = self.version_file.read_text(encoding="utf-8").strip()
        if not re.fullmatch(r"\d+\.\d+\.\d+", v):
            reporter.record(
                self.NAME, "corporate version is semver", False,
                f"value: {v!r}",
            )
            return None
        reporter.record(self.NAME, "corporate version file exists", True, f"version={v}")
        return v

    def _load_manifest(self, reporter: "Reporter") -> Optional[dict]:
        if not self.manifest_path.exists():
            reporter.record(
                self.NAME, "manifest file exists", False,
                f"missing: {self.manifest_path.relative_to(self.ctx.REPO_ROOT)}",
            )
            return None
        try:
            data = json.loads(self.manifest_path.read_text(encoding="utf-8"))
            reporter.record(self.NAME, "manifest file exists", True)
            return data
        except json.JSONDecodeError as e:
            reporter.record(
                self.NAME, "manifest is valid JSON", False, f"{e}"
            )
            return None

    def _policy_header_version(self, text: str, expected: str) -> tuple[bool, str]:
        m = re.search(r"^\|\s*Vers[aã]o\s*\|\s*(\d+\.\d+\.\d+)\s*\|", text, re.M)
        if not m:
            return False, "<not found>"
        return m.group(1) == expected, m.group(1)

    def _missing_sections(self, text: str) -> list[str]:
        missing = []
        for pat in _REQUIRED_SECTIONS:
            if not re.search(pat, text, re.M):
                missing.append(pat)
        return missing

    def _slice_section(self, text: str, header_pat: str) -> Optional[str]:
        m = re.search(header_pat, text, re.M)
        if not m:
            return None
        start = m.start()
        tail = text[start + 1:]
        candidates = [
            mm.start() for mm in (
                re.search(r"^##\s", tail, re.M),
                re.search(r"\n---\s*$", tail, re.M),
            ) if mm
        ]
        end = start + 1 + min(candidates) if candidates else len(text)
        return text[start:end]
