"""
Regression tests for ava-stack-dotnet-backend structural contract.

Validates source code generated by the F4 Stack .NET agent against
the F4 .NET structural contract defined in docs/architecture/f4-dotnet-contract.md.

Run:
    pytest tests/ava-fabric-agents/tech-stack/test_coder_dotnet_backend_contract.py
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
import os
from pathlib import Path
from typing import List, Set, Tuple

import pytest
import yaml


def _default_source_path() -> Path:
    env = os.getenv("PROCESSAERP005_SOURCE_PATH")
    if env:
        return Path(env)
    # Multi-root workspace: processaERP-005 may live outside the IMFAI repo root.
    repo = Path(__file__).resolve().parents[4]
    candidates = [
        repo.parent / "processaERP-005",
        Path.home() / "Downloads" / "processaERP-005",
        Path("c:/_git/fix/processaERP-005"),
    ]
    for candidate in candidates:
        path = candidate / "outputs" / "tobe" / "source-code"
        if path.exists():
            return path
    # Fallback: best-effort default so pytest shows a clear skip message.
    return candidates[-1] / "outputs" / "tobe" / "source-code"


@pytest.fixture(scope="module")
def source_code_path() -> Path:
    """Path to generated source-code root."""
    path = _default_source_path()
    if not path.exists():
        pytest.skip(f"Generated source code not found at {path}")
    return path


@pytest.fixture(scope="module")
def backend_path(source_code_path: Path) -> Path:
    """Path to backend folder."""
    path = source_code_path / "backend"
    assert path.exists(), f"backend folder not found: {path}"
    return path


@pytest.fixture(scope="module")
def bc_names(backend_path: Path, prefix: str) -> List[str]:
    """Discover Bounded Context names from the solution file."""
    sln = backend_path / f"{prefix}.sln"
    if not sln.exists():
        pytest.skip(f"Solution file not found: {sln}")
    pattern = re.compile(rf'"{re.escape(prefix)}\.(\w+)\.Api"')
    names = set()
    for line in sln.read_text(encoding="utf-8").splitlines():
        match = pattern.search(line)
        if match:
            names.add(match.group(1))
    return sorted(names)


@pytest.fixture(scope="module")
def prefix() -> str:
    """Project / solution prefix for ProcessaERP-005."""
    return "ProcessaERP005"


def _api_dir(backend_path: Path, prefix: str, bc: str) -> Path:
    """Return the API project directory respecting src/{BC} layout."""
    legacy = backend_path / bc / f"{prefix}.{bc}.Api"
    standard = backend_path / "src" / bc / f"{prefix}.{bc}.Api"
    return standard if standard.exists() or not legacy.exists() else legacy


def _discover_api_projects(backend_path: Path, bc_names: List[str], prefix: str) -> List[Tuple[str, Path]]:
    """Return list of (bcName, csprojPath) for all API projects."""
    result = []
    for bc in bc_names:
        api_dir = _api_dir(backend_path, prefix, bc)
        csproj = api_dir / f"{prefix}.{bc}.Api.csproj"
        if csproj.exists():
            result.append((bc, csproj))
    return result


class TestApiProjectContract:
    """Ensure every BC.Api .csproj follows the structural contract."""

    def test_api_uses_web_sdk(self, backend_path: Path, bc_names: List[str], prefix: str):
        for bc, csproj in _discover_api_projects(backend_path, bc_names, prefix):
            root = ET.parse(csproj).getroot()
            sdk = root.get("Sdk")
            assert sdk == "Microsoft.NET.Sdk.Web", (
                f"{csproj}: expected Microsoft.NET.Sdk.Web, got {sdk}"
            )

    def test_api_output_type_is_exe(self, backend_path: Path, bc_names: List[str], prefix: str):
        for bc, csproj in _discover_api_projects(backend_path, bc_names, prefix):
            root = ET.parse(csproj).getroot()
            ns = {"msbuild": "http://schemas.microsoft.com/developer/msbuild/2003"}
            output_type = root.findtext(".//msbuild:OutputType", namespaces=ns)
            if output_type is None:
                output_type = root.findtext(".//OutputType")
            assert output_type == "Exe", (
                f"{csproj}: expected <OutputType>Exe</OutputType>, got {output_type}"
            )

    def test_api_has_required_project_references(
        self,
        backend_path: Path,
        bc_names: List[str],
        prefix: str,
    ):
        for bc, csproj in _discover_api_projects(backend_path, bc_names, prefix):
            required_refs = {
                f"{prefix}.{bc}.Application",
                f"{prefix}.{bc}.Infrastructure",
                f"{prefix}.Shared.Domain",
                f"{prefix}.Shared.Infrastructure",
            }
            root = ET.parse(csproj).getroot()
            ns = {"msbuild": "http://schemas.microsoft.com/developer/msbuild/2003"}
            refs = {e.get("Include", "") for e in root.findall(".//msbuild:ProjectReference", namespaces=ns)}
            if not refs:
                refs = {e.get("Include", "") for e in root.findall(".//ProjectReference")}
            # Include may contain relative path; normalize to project name.
            ref_names = {Path(r).stem for r in refs if r}
            missing = required_refs - ref_names
            assert not missing, f"{csproj}: missing references: {missing}\nfound: {ref_names}"


class TestApiProgramContract:
    """Ensure every BC.Api has an entry point and wires shared infrastructure."""

    def test_program_cs_exists(self, backend_path: Path, bc_names: List[str], prefix: str):
        for bc in bc_names:
            program = _api_dir(backend_path, prefix, bc) / "Program.cs"
            assert program.exists(), f"Missing entry point: {program}"

    def test_dependency_injection_calls_shared_infrastructure(
        self,
        backend_path: Path,
        bc_names: List[str],
        prefix: str,
    ):
        pattern = re.compile(r"AddSharedInfrastructure\(\)")
        for bc in bc_names:
            api_dir = _api_dir(backend_path, prefix, bc)
            candidates = [api_dir / "DependencyInjection.cs"] + list(api_dir.rglob("DependencyInjection.cs"))
            hits = {c for c in candidates if c.exists() and pattern.search(c.read_text(encoding="utf-8"))}
            assert hits, (
                f"{prefix}.{bc}.Api: AddSharedInfrastructure() call not found "
                "in DependencyInjection.cs or Program.cs"
            )


class TestContainerContract:
    """Ensure docker-compose.yml declares all BC services and dependencies."""

    def test_compose_declares_sql_redis_and_all_backends(
        self,
        source_code_path: Path,
        bc_names: List[str],
    ):
        compose_file = source_code_path / "docker-compose.yml"
        if not compose_file.exists():
            pytest.skip(f"{compose_file} not found")

        compose = yaml.safe_load(compose_file.read_text(encoding="utf-8"))
        services = compose.get("services", {})

        assert "sql" in services, "Missing 'sql' service in docker-compose.yml"
        assert "redis" in services, "Missing 'redis' service in docker-compose.yml"

        def normalize(name: str) -> str:
            return name.lower().replace("-", "").replace("_", "").replace(" ", "")

        backend_service_names: Set[str] = {
            name for name in services if name not in {"sql", "redis", "frontend"}
        }
        normalized_services = {normalize(n) for n in backend_service_names}

        missing = []
        for bc in bc_names:
            if normalize(bc) not in normalized_services and not any(
                normalize(bc) in normalize(s) or normalize(s) in normalize(bc)
                for s in backend_service_names
            ):
                missing.append(bc)
        assert not missing, (
            f"docker-compose.yml missing backend services for BCs: {missing}\n"
            f"services found: {sorted(backend_service_names)}"
        )
