#!/usr/bin/env python3
"""
Draw.io Governance Validator
==============================

Validates that .drawio files generated by IMFAI agents comply with
the rules defined in shared/drawio-governance.md:

  1. AS-IS .drawio files present  (asis/diagrams/)
  2. TO-BE .drawio files present  (tobe/diagrams/)
  3. Edge style governance        (rounded=1, orthogonalLoop, jumpStyle=arc)
  4. Multi-page consolidation     (diagrama-*.drawio has >=2 <diagram> tabs)

Usage:
    python validate_drawio_integration.py --project {PROJECT_NAME}

Author: AVA Fabric Apps Agents
Date: 2026-05
"""

import argparse
import re
from pathlib import Path


class Colors:
    RESET  = '\033[0m'
    GREEN  = '\033[92m'
    RED    = '\033[91m'
    YELLOW = '\033[93m'
    BLUE   = '\033[94m'
    BOLD   = '\033[1m'


def print_header(text):
    print(f"\n{Colors.BOLD}{Colors.BLUE}{'\u2550' * 70}{Colors.RESET}")
    print(f"{Colors.BOLD}{Colors.BLUE}  {text}{Colors.RESET}")
    print(f"{Colors.BOLD}{Colors.BLUE}{'\u2550' * 70}{Colors.RESET}\n")


def print_check(passed, message):
    symbol = f"{Colors.GREEN}\u2705{Colors.RESET}" if passed else f"{Colors.RED}\u274c{Colors.RESET}"
    print(f"  {symbol} {message}")
    return passed


# ---------------------------------------------------------------------------
# Check 1 — AS-IS .drawio files
# ---------------------------------------------------------------------------

ASIS_EXPECTED = [
    "c4-context.drawio",
    "c4-container.drawio",
    "c4-component.drawio",
    "component-diagram.drawio",
    "diagrama-componentes.drawio",
]


def validate_asis_drawio(project_name: str) -> bool:
    """Check AS-IS .drawio files in asis/diagrams/"""
    print_header("1. AS-IS Draw.io Files  (asis/diagrams/)")

    diag_dir = Path(f'projects/{project_name}/outputs/asis/diagrams')
    if not diag_dir.exists():
        print_check(False, f"Directory not found: {diag_dir}")
        return False
    print_check(True, f"Directory exists: {diag_dir}")

    found = []
    for name in ASIS_EXPECTED:
        p = diag_dir / name
        ok = p.exists() and p.stat().st_size > 50
        print_check(ok, f"{name}  ({p.stat().st_size if p.exists() else 0} bytes)")
        if ok:
            found.append(p)

    # Sequence diagrams (variable names — count any match)
    seq_files = list(diag_dir.glob('diagrama-sequencia-*.drawio'))
    seq_ok = len(seq_files) >= 1
    print_check(seq_ok, f"diagrama-sequencia-*.drawio  ({len(seq_files)} found, min 1)")

    return len(found) >= 3  # At least 3 of the 5 expected files


# ---------------------------------------------------------------------------
# Check 2 — TO-BE .drawio files
# ---------------------------------------------------------------------------

TOBE_EXPECTED = [
    "c4-context.drawio",
    "c4-container.drawio",
    "c4-component.drawio",
    "class-diagram.drawio",
    "component-diagram.drawio",
    "diagrama-tobe.drawio",
]


def validate_tobe_drawio(project_name: str) -> bool:
    """Check TO-BE .drawio files in tobe/diagrams/"""
    print_header("2. TO-BE Draw.io Files  (tobe/diagrams/)")

    diag_dir = Path(f'projects/{project_name}/outputs/tobe/diagrams')
    gantt    = Path(f'projects/{project_name}/outputs/tobe/migration-gantt.drawio')

    if not diag_dir.exists():
        print_check(False, f"Directory not found: {diag_dir}")
        print_check(False, "Skipping all TO-BE checks")
        return False
    print_check(True, f"Directory exists: {diag_dir}")

    found = []
    for name in TOBE_EXPECTED:
        p = diag_dir / name
        ok = p.exists() and p.stat().st_size > 50
        print_check(ok, f"{name}  ({p.stat().st_size if p.exists() else 0} bytes)")
        if ok:
            found.append(p)

    # Migration Gantt
    gantt_ok = gantt.exists() and gantt.stat().st_size > 50
    print_check(gantt_ok, f"migration-gantt.drawio  ({gantt.stat().st_size if gantt.exists() else 0} bytes)")

    return len(found) >= 3


# ---------------------------------------------------------------------------
# Check 3 — Edge style governance
# ---------------------------------------------------------------------------

REQUIRED_EDGE_ATTRS = [
    "edgeStyle=orthogonalEdgeStyle",
    "rounded=1",
    "orthogonalLoop=1",
    "jettySize=auto",
    "jumpStyle=arc",
]
FORBIDDEN_EDGE_ATTR = "rounded=0"


def _check_edge_styles(path: Path) -> tuple[int, int, list]:
    """Return (edges_checked, violations, violation_messages)"""
    xml = path.read_text(encoding='utf-8', errors='replace')
    edges = re.findall(r'<mxCell[^>]+edge="1"[^>]*/>', xml)
    edges += re.findall(r'<mxCell[^>]+edge="1"[^>]*>.*?</mxCell>', xml, re.DOTALL)

    violations = []
    for edge in edges:
        if FORBIDDEN_EDGE_ATTR in edge:
            violations.append(f"  found '{FORBIDDEN_EDGE_ATTR}' in: {edge[:80]}")
        for attr in REQUIRED_EDGE_ATTRS:
            if attr not in edge:
                violations.append(f"  missing '{attr}' in edge: {edge[:80]}")
    return len(edges), len(violations), violations


def validate_edge_styles(project_name: str) -> bool:
    """Scan all generated .drawio files for governance-compliant edge styles."""
    print_header("3. Edge Style Governance  (Rule 1 — shared/drawio-governance.md)")

    search_dirs = [
        Path(f'projects/{project_name}/outputs/asis/diagrams'),
        Path(f'projects/{project_name}/outputs/tobe/diagrams'),
        Path(f'projects/{project_name}/outputs/tobe'),
    ]

    all_files: list[Path] = []
    for d in search_dirs:
        if d.exists():
            all_files.extend(d.glob('*.drawio'))

    if not all_files:
        print_check(False, "No .drawio files found to validate")
        return False

    total_edges = 0
    total_violations = 0
    files_with_violations = 0

    for f in all_files:
        edges, viols, msgs = _check_edge_styles(f)
        total_edges += edges
        total_violations += viols
        ok = viols == 0
        if not ok:
            files_with_violations += 1
        label = f"{f.parent.name}/{f.name}  ({edges} edges, {viols} violations)"
        print_check(ok, label)
        if msgs and viols > 0:
            for m in msgs[:3]:  # show first 3 violation details
                print(f"    {Colors.YELLOW}{m[:110]}{Colors.RESET}")
            if len(msgs) > 3:
                print(f"    {Colors.YELLOW}  ... and {len(msgs)-3} more{Colors.RESET}")

    print(f"\n  {Colors.BLUE}\u2139\ufe0f  Total: {total_edges} edges scanned, {total_violations} violations in {files_with_violations}/{len(all_files)} files{Colors.RESET}")
    return total_violations == 0


# ---------------------------------------------------------------------------
# Check 4 — Multi-page consolidation
# ---------------------------------------------------------------------------

def validate_multi_page(project_name: str) -> bool:
    """Check that consolidated .drawio files have >=2 <diagram> tabs."""
    print_header("4. Multi-Page Consolidation  (consolidated drawio files)")

    candidates = [
        Path(f'projects/{project_name}/outputs/asis/diagrams/diagrama-componentes.drawio'),
        Path(f'projects/{project_name}/outputs/tobe/diagrams/diagrama-tobe.drawio'),
    ]

    any_found = False
    all_ok = True
    for p in candidates:
        if not p.exists():
            print_check(False, f"{p.parent.name}/{p.name}  (not found)")
            all_ok = False
            continue
        xml = p.read_text(encoding='utf-8', errors='replace')
        tabs = xml.count('<diagram ')
        ok = tabs >= 2
        print_check(ok, f"{p.parent.name}/{p.name}  ({tabs} <diagram> tabs, min 2)")
        if not ok:
            all_ok = False
        any_found = True

    return any_found and all_ok


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

def run_full_validation(project_name: str) -> bool:
    print(f"\n{Colors.BOLD}Draw.io Governance Validator{Colors.RESET}")
    print(f"Project : {project_name}")
    print(f"Governed by : src/modules/ava-fabric-agents/shared/drawio-governance.md\n")

    results = {
        "AS-IS Draw.io files"    : validate_asis_drawio(project_name),
        "TO-BE Draw.io files"    : validate_tobe_drawio(project_name),
        "Edge style governance"  : validate_edge_styles(project_name),
        "Multi-page consolidation": validate_multi_page(project_name),
    }

    print_header("VALIDATION SUMMARY")
    passed = sum(results.values())
    total  = len(results)

    for name, result in results.items():
        symbol = f"{Colors.GREEN}\u2705{Colors.RESET}" if result else f"{Colors.RED}\u274c{Colors.RESET}"
        print(f"  {symbol} {name}")

    print(f"\n  {Colors.BOLD}Score: {passed}/{total} checks passed{Colors.RESET}")

    if passed == total:
        print(f"\n  {Colors.GREEN}{Colors.BOLD}\U0001f389 ALL VALIDATIONS PASSED{Colors.RESET}")
        print(f"  {Colors.GREEN}Draw.io files comply with shared/drawio-governance.md.{Colors.RESET}\n")
    else:
        print(f"\n  {Colors.YELLOW}{Colors.BOLD}\u26a0\ufe0f  SOME CHECKS FAILED{Colors.RESET}")
        print(f"  {Colors.YELLOW}See details above. Review shared/drawio-governance.md.{Colors.RESET}\n")

    return passed == total


def main():
    parser = argparse.ArgumentParser(description="Validate Draw.io Governance Compliance")
    parser.add_argument('--project', required=True, help='Project name (e.g., Meu-ERP)')
    args = parser.parse_args()
    success = run_full_validation(args.project)
    raise SystemExit(0 if success else 1)


if __name__ == '__main__':
    main()


import argparse
import json
import re
from pathlib import Path


class Colors:
    RESET = '\033[0m'
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    BOLD = '\033[1m'


def print_header(text):
    print(f"\n{Colors.BOLD}{Colors.BLUE}{'═' * 70}{Colors.RESET}")
    print(f"{Colors.BOLD}{Colors.BLUE}  {text}{Colors.RESET}")
    print(f"{Colors.BOLD}{Colors.BLUE}{'═' * 70}{Colors.RESET}\n")


def print_check(passed, message):
    symbol = f"{Colors.GREEN}✅{Colors.RESET}" if passed else f"{Colors.RED}❌{Colors.RESET}"
    print(f"  {symbol} {message}")
    return passed


def validate_template_patch():
    """Check if template has been patched with Draw.io integration"""
    print_header("1. Validating Template Patch")
    
    template_path = Path('src/modules/ava-fabric-agents/summary/templates/html/summary-template.html')
    
    if not template_path.exists():
        print_check(False, f"Template not found: {template_path}")
        return False
    
    print_check(True, "Template file exists")
    
    html = template_path.read_text(encoding='utf-8')
    
    # Check for key patches
    checks = {
        "Navigation items": 'onclick="nav(\'s-f1-diagrams-c4\',this)"',
        "CSS styles": '.drawio-container{',
        "Section HTML": '<section id="s-f1-diagrams-c4"',
        "JavaScript functions": 'function renderDrawioViewer(',
        "Data placeholder": '{{DRAWIO_FILES_JSON}}',
        "i18n PT": '"nav-diagrams-c4"',
        "i18n EN": '"pg-diagrams-c4"',
    }
    
    all_passed = True
    for name, marker in checks.items():
        passed = marker in html
        all_passed &= print_check(passed, f"{name} present")
    
    # Check backup exists
    backup_path = template_path.with_suffix('.html.backup')
    print_check(backup_path.exists(), f"Backup exists: {backup_path.name}")
    
    return all_passed


def validate_drawio_files(project_name):
    """Check if .drawio files have been generated"""
    print_header("2. Validating .drawio Files")
    
    drawio_dir = Path(f'projects/{project_name}/outputs/asis/drawio')
    
    if not drawio_dir.exists():
        print_check(False, f"Drawio directory not found: {drawio_dir}")
        print(f"\n  {Colors.YELLOW}ℹ️  Run: python generate_drawio_from_mermaid.py --project {project_name}{Colors.RESET}")
        return False
    
    print_check(True, "Drawio directory exists")
    
    expected_files = [
        "AS-IS-C4-Diagrams.drawio",
        "AS-IS-Overall-Architecture.drawio",
        "AS-IS-BPMN-Processes.drawio",
        "AS-IS-Sequence-Diagrams.drawio"
    ]
    
    found = 0
    for filename in expected_files:
        file_path = drawio_dir / filename
        exists = file_path.exists()
        
        if exists:
            # Count pages
            xml = file_path.read_text(encoding='utf-8')
            pages = xml.count('<diagram ')
            print_check(True, f"{filename} ({pages} pages)")
            found += 1
        else:
            print_check(False, f"{filename} not found")
    
    print(f"\n  {Colors.BLUE}ℹ️  Found {found}/4 .drawio files{Colors.RESET}")
    
    return found >= 2  # At least 2 files should exist


def validate_builder_integration():
    """Check if build_summary_comprehensive.py has load_drawio_files()"""
    print_header("3. Validating Builder Integration")
    
    builder_path = Path('src/modules/ava-fabric-agents/summary/utils/build_summary_comprehensive.py')
    
    if not builder_path.exists():
        print_check(False, f"Builder not found: {builder_path}")
        return False
    
    print_check(True, "Builder file exists")
    
    code = builder_path.read_text(encoding='utf-8')
    
    checks = {
        "load_drawio_files() function": 'def load_drawio_files(',
        "Function call in build_summary_html": 'drawio_files = load_drawio_files(',
        "JSON injection": "html.replace('{{DRAWIO_FILES_JSON}}'",
    }
    
    all_passed = True
    for name, marker in checks.items():
        passed = marker in code
        all_passed &= print_check(passed, name)
    
    return all_passed


def validate_summary_html(project_name):
    """Check if generated Summary HTML contains Draw.io data"""
    print_header("4. Validating Summary HTML Output")
    
    summary_dir = Path(f'projects/{project_name}/outputs/summary')
    
    if not summary_dir.exists():
        print_check(False, f"Summary directory not found: {summary_dir}")
        return False
    
    # Find most recent summary file
    summary_files = list(summary_dir.glob('AVA-FABRIC-SUMMARY-*.html'))
    
    if not summary_files:
        print_check(False, "No summary HTML files found")
        print(f"\n  {Colors.YELLOW}ℹ️  Run: python build_summary_comprehensive.py --project {project_name}{Colors.RESET}")
        return False
    
    latest_file = max(summary_files, key=lambda p: p.stat().st_mtime)
    print_check(True, f"Summary HTML found: {latest_file.name}")
    
    html = latest_file.read_text(encoding='utf-8')
    
    # Check file size (should be ~180KB not 24KB)
    size_kb = len(html) / 1024
    size_ok = size_kb > 100
    print_check(size_ok, f"File size: {size_kb:.1f} KB (expected >100 KB)")
    
    # Check for Draw.io data object
    checks = {
        "drawioFiles object": 'drawioFiles:',
        "renderDrawioViewer function": 'function renderDrawioViewer(',
        "renderAllDrawioViewers call": 'renderAllDrawioViewers();',
        "C4 section": 'id="s-f1-diagrams-c4"',
        "Overall section": 'id="s-f1-diagrams-overall"',
        "BPMN section": 'id="s-f1-diagrams-bpmn"',
        "Sequence section": 'id="s-f1-diagrams-sequence"',
    }
    
    all_passed = True
    for name, marker in checks.items():
        passed = marker in html
        all_passed &= print_check(passed, name)
    
    # Extract drawioFiles data
    match = re.search(r'drawioFiles:\s*(\{[^}]+\})', html)
    if match:
        try:
            # This is a simplified check - actual parsing would be more complex
            drawio_data_snippet = match.group(1)[:100]
            print_check(True, f"drawioFiles data present: {drawio_data_snippet}...")
        except:
            print_check(False, "drawioFiles data malformed")
    else:
        print_check(False, "drawioFiles data not found")
    
    return all_passed and size_ok


def run_full_validation(project_name):
    """Run complete validation suite"""
    print(f"\n{Colors.BOLD}Draw.io Enterprise Integration Validator{Colors.RESET}")
    print(f"Project: {project_name}\n")
    
    results = {
        "Template Patch": validate_template_patch(),
        "Drawio Files": validate_drawio_files(project_name),
        "Builder Integration": validate_builder_integration(),
        "Summary HTML": validate_summary_html(project_name),
    }
    
    # Summary
    print_header("VALIDATION SUMMARY")
    
    passed = sum(results.values())
    total = len(results)
    
    for name, result in results.items():
        symbol = f"{Colors.GREEN}✅{Colors.RESET}" if result else f"{Colors.RED}❌{Colors.RESET}"
        print(f"  {symbol} {name}")
    
    print(f"\n  {Colors.BOLD}Score: {passed}/{total} checks passed{Colors.RESET}")
    
    if passed == total:
        print(f"\n  {Colors.GREEN}{Colors.BOLD}🎉 ALL VALIDATIONS PASSED!{Colors.RESET}")
        print(f"  {Colors.GREEN}Draw.io integration is fully functional.{Colors.RESET}\n")
        return True
    else:
        print(f"\n  {Colors.YELLOW}{Colors.BOLD}⚠️  INCOMPLETE INSTALLATION{Colors.RESET}")
        print(f"  {Colors.YELLOW}Some checks failed. See details above.{Colors.RESET}\n")
        return False


def main():
    parser = argparse.ArgumentParser(description="Validate Draw.io Enterprise Integration")
    parser.add_argument('--project', required=True, help='Project name (e.g., database-comparer-examples)')
    args = parser.parse_args()
    
    success = run_full_validation(args.project)
    
    exit(0 if success else 1)


if __name__ == '__main__':
    main()
