#!/usr/bin/env python3
"""Materialize every mandatory F3S output without hiding incomplete planning.

Missing artifacts are persisted as explicit recovery placeholders. This keeps
the pipeline observable and allows downstream reporting to continue, while the
F3S exit gate blocks code generation until every placeholder is replaced by a
real producer output.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
PLACEHOLDER_MARKER = "recovery_placeholder"


def _now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def _write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp")
    temp.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temp.replace(path)


def _write_markdown(path: Path, title: str, producer: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"<!-- {PLACEHOLDER_MARKER} -->\n# {title}\n\n"
        "Este artefato obrigatório foi materializado pelo reconciliador porque "
        f"`{producer}` não persistiu uma saída utilizável.\n\n"
        "**Status:** INCOMPLETE - não consumir para geração de código.\n",
        encoding="utf-8",
    )


def _is_placeholder(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        if path.suffix == ".json":
            value = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(value, dict) or value.get(PLACEHOLDER_MARKER):
                return True
            required_by_name = {
                "plan-graph.json": {"schema_version", "feature", "groups", "files"},
                "task-fragment.json": {"schema_version", "feature", "entries"},
                "traceability.json": {"schema_version", "entries", "execution_order"},
                "tasks-progress.json": {"schema_version", "tasks"},
                "checks-report.json": {"total", "failed", "results"},
                "compliance-status.json": {"verdict", "constitution_items", "findings"},
                "execution-log.json": {"phase", "status"},
                "wave-spec-manifest.json": {"features"},
            }
            return not required_by_name.get(path.name, set()).issubset(value)
        return PLACEHOLDER_MARKER in path.read_text(encoding="utf-8", errors="ignore")[:500]
    except (OSError, json.JSONDecodeError):
        return True


def _placeholder(path: Path, *, kind: str, project: str, trace_id: str,
                 feature: str = "", producer: str) -> None:
    if path.is_file() and path.stat().st_size > 0:
        return
    if kind == "markdown":
        _write_markdown(path, path.stem.replace("-", " ").title(), producer)
        return
    value: dict[str, Any] = {
        "schema_version": "recovery-1.0.0",
        "project": project,
        "trace_id": trace_id,
        "status": "INCOMPLETE",
        PLACEHOLDER_MARKER: True,
        "expected_producer": producer,
        "generated_at": _now(),
    }
    if feature:
        value["feature"] = feature
    if path.name == "traceability.json":
        value.update({
            "schema_version": "4.0.0", "total_tasks": 0,
            "graph_checksum": hashlib.sha256(b"[]").hexdigest(),
            "dependency_edges": [], "execution_order": [],
            "execution_waves": [], "entries": [],
        })
    elif path.name == "tasks-progress.json":
        value.update({"schema_version": "3.0.0", "tasks": []})
    elif path.name == "compliance-status.json":
        value.update({
            "schema_version": "1.0.0", "verdict": "BLOCKED",
            "constitution_items": 0, "items_honored": 0,
            "findings": [{
                "id": "RECOVERY-001", "severity": "high",
                "summary": "Compliance output was not generated by its owning agent.",
                "remediation": "Re-run ava-speckit-compliance after replacing placeholders.",
            }],
        })
    elif path.name == "checks-report.json":
        value.update({"total": 0, "passed": 0, "failed": 1, "all_passed": False,
                      "results": []})
    _write_json(path, value)


def _try_rebuild(project: str, speckit: Path, root: Path) -> dict[str, Any]:
    """Reconstrói traceability/progresso quando há fragments e o artefato falta.

    Reusa `speckit_task_compiler.compile_project` — a MESMA consolidação
    best-effort da wave5b, não uma segunda implementação. Duas lógicas de
    consolidação divergiriam, e a de menos uso divergiria em silêncio.

    Nunca levanta e nunca piora o estado: sem fragments, ou com o artefato já
    válido em disco, é no-op.
    """
    resultado: dict[str, Any] = {"attempted": False, "rebuilt": False, "detail": ""}
    traceability = speckit / "traceability.json"
    if traceability.is_file() and not _is_placeholder(traceability):
        resultado["detail"] = "traceability válido em disco — nada a reconstruir"
        return resultado

    fragments = sorted((speckit / "specs").glob("*/task-fragment.json"))
    legiveis = [f for f in fragments if f.is_file() and not _is_placeholder(f)]
    if not legiveis:
        resultado["detail"] = "nenhum task-fragment recuperável"
        return resultado

    resultado["attempted"] = True
    try:
        import speckit_task_compiler  # noqa: PLC0415
        saida = speckit_task_compiler.compile_project(project, root, write=True)
        resultado["rebuilt"] = bool(saida.get("entries"))
        resultado["entries"] = len(saida.get("entries") or [])
        resultado["detail"] = (
            f"reconstruído a partir de {len(legiveis)} fragment(s): "
            f"{resultado['entries']} entry(ies)")
    except Exception as exc:  # noqa: BLE001 — reconstrução é best-effort
        resultado["detail"] = f"reconstrução falhou: {type(exc).__name__}: {exc}"
    return resultado


def reconcile(project: str, stage: str, repo_root: Path | None = None) -> dict[str, Any]:
    root = repo_root or REPO_ROOT
    speckit = root / "projects" / project / "outputs" / "tobe" / "speckit"
    manifest_path = speckit / "wave-spec-manifest.json"
    if not manifest_path.is_file():
        return {"status": "ERROR", "detail": f"manifest absent: {manifest_path}"}
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {"status": "ERROR", "detail": f"invalid manifest: {exc}"}

    trace_id = str(manifest.get("trace_id") or "")
    expected: list[tuple[Path, str, str]] = [
        (speckit / "constitution.md", "markdown", "ava-speckit-constitution"),
        (manifest_path, "json", "speckit_wave_manifest.py"),
        (speckit / "traceability.json", "json", "speckit_task_compiler.py"),
        (speckit / "tasks-progress.json", "json", "task_ledger.py"),
        (speckit / "checks-report.json", "json", "src.shared.checks"),
    ]
    for item in manifest.get("features") or []:
        feature = str(item.get("feature") or "")
        if not feature:
            continue
        directory = speckit / "specs" / feature
        expected.append((directory / "spec.md", "markdown", "ava-speckit-specification"))
        if item.get("codegen"):
            expected.extend([
                (directory / "plan.md", "markdown", "ava-speckit-planning"),
                (directory / "plan-graph.json", "json", "ava-speckit-planning"),
                (directory / "task-fragment.json", "json", "ava-speckit-tasks"),
                (directory / "tasks.md", "markdown", "speckit_task_compiler.py"),
            ])

    if stage == "final":
        execution_log = speckit / "execution-log.json"
        if not execution_log.is_file() or _is_placeholder(execution_log):
            features = manifest.get("features") or []
            codegen_features = [item for item in features if item.get("codegen")]
            _write_json(execution_log, {
                "schema_version": "1.0.0", "agent": "speckit_output_reconciler.py",
                "phase": "F3S", "event": "reconciliation", "status": "in_progress",
                "project": project, "trace_id": trace_id, "generated_at": _now(),
                "manifest_waves": len(features),
                "specs_present": sum(
                    (speckit / "specs" / str(item.get("feature")) / "spec.md").is_file()
                    for item in features),
                "codegen_waves": len(codegen_features),
            })
        expected.extend([
            (speckit / "compliance-report.md", "markdown", "ava-speckit-compliance"),
            (speckit / "compliance-status.json", "json", "ava-speckit-compliance"),
            (execution_log, "json", "speckit_output_reconciler.py"),
        ])
        progress = speckit / "ava-agents-progress.txt"
        if not progress.is_file() or progress.stat().st_size == 0:
            progress.write_text(
                f"F3S reconciliation stage=final project={project} generated_at={_now()}\n",
                encoding="utf-8",
            )
            expected.append((progress, "markdown", "task_ledger.py"))

    # Antes de materializar placeholder, TENTAR RECONSTRUIR. Um placeholder
    # antigo em disco nunca era substituído (`_placeholder` sai cedo se o
    # arquivo existe), então uma consolidação que falhou uma vez ficava
    # cristalizada como "artefato perdido" para sempre — mesmo depois de o
    # defeito ser corrigido e os fragments estarem íntegros.
    rebuilt = _try_rebuild(project, speckit, root)

    materialized: list[str] = []
    for path, kind, producer in expected:
        if not path.is_file() or path.stat().st_size == 0:
            feature = path.parent.name if path.parent.parent.name == "specs" else ""
            _placeholder(path, kind=kind, project=project, trace_id=trace_id,
                         feature=feature, producer=producer)
            materialized.append(str(path.relative_to(speckit)))

    placeholders = sorted(
        str(path.relative_to(speckit)) for path, _, _ in expected if _is_placeholder(path)
    )
    status = "READY" if not placeholders else "INCOMPLETE"
    report = {
        "schema_version": "1.0.0", "project": project, "trace_id": trace_id,
        "stage": stage, "status": status, "generated_at": _now(),
        "materialized": materialized, "placeholders": placeholders,
        "expected_count": len(expected),
        # Reconstrução tentada/realizada. Sem isto, criar um placeholder e
        # reconstruir um artefato real ficavam indistinguíveis no relatório.
        "rebuild": rebuilt,
    }
    if stage == "final":
        execution_log = speckit / "execution-log.json"
        execution_data = json.loads(execution_log.read_text(encoding="utf-8"))
        execution_data["status"] = "completed" if status == "READY" else "incomplete"
        execution_data["completeness_status"] = status
        execution_data["f4_released"] = status == "READY"
        _write_json(execution_log, execution_data)
    _write_json(speckit / "completeness-status.json", report)
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", "-p", required=True)
    parser.add_argument("--stage", choices=["planning", "final"], required=True)
    parser.add_argument("--json", action="store_true", dest="as_json")
    args = parser.parse_args(argv)
    result = reconcile(args.project, args.stage)
    if args.as_json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(f"speckit-output-reconciler: {result.get('status')} — {result}")
    return 2 if result.get("status") == "ERROR" else 0


if __name__ == "__main__":
    sys.exit(main())