import { defineConfig } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Playwright configuration template for AVA API black-box tests.
 * Generated by ava-qa-bridge-fastqa-tobe.
 *
 * Placeholders to replace:
 *   {PROJECT_NAME}  — name of the project (e.g. "MeuERP")
 *   {API_BASE_URL}  — default API base URL (e.g. "http://localhost:5000")
 *   {OUTPUT_DIR}    — test results output directory (e.g. "./test-results")
 */
export default defineConfig({
  testDir: './tests',
  outputDir: process.env.OUTPUT_DIR || './test-results',
  timeout: 30_000,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: './playwright-report' }],
    ['json', { outputFile: './test-results/results.json' }],
    ['junit', { outputFile: './test-results/results.xml' }],
  ],
  use: {
    baseURL: process.env.API_BASE_URL || '{API_BASE_URL}',
    extraHTTPHeaders: {
      'Accept': 'application/json',
    },
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'api-smoke',
      grep: /@smoke/,
    },
    {
      name: 'api-security',
      grep: /@security/,
    },
    {
      name: 'api-regression',
      grep: /@regression/,
    },
  ],
});
